jwt:
  header: Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400


server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    #    database-platform: mysql
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/cherrypick?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root-pass
  flyway:
    user: root
    schemas: cherrypick
    url: jdbc:mysql://localhost:3306/cherrypick?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true
  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 351036677214-741pvp8bs3hgcdgropss0j5j077jju6e.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          naver:
            clientId: D5DK8U6m0r772gZ9Vcsd
            clientSecret: EYDkcRAg9N
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
            authorization-grant-type: authorization_code
            client-name: Naver
          kakao:
            clientId: 00483c0f0bb297db07d80695b0e646ee
            client-name: Kakao
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
