INSERT INTO USER (ID, PROVIDER_ID, PASSWORD, NICKNAME, ACTIVATED, AUTHORITY) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 1, 'ROLE_ADMIN');
INSERT INTO USER (ID, PROVIDER_ID, PASSWORD, NICKNAME, ACTIVATED, AUTHORITY) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 1, 'ROLE_USER');
