INSERT INTO USER (ID, PROVIDER_ID, PASSWORD, NICKNAME, ACTIVATED, AUTHORITY) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 1, 'ROLE_ADMIN');
INSERT INTO USER (ID, PROVIDER_ID, PASSWORD, NICKNAME, ACTIVATED, AUTHORITY) VALUES (2, 'user', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'user', 1, 'ROLE_USER');
INSERT INTO USER (ID, PROVIDER_ID, PASSWORD, NICKNAME, ACTIVATED, AUTHORITY) VALUES (3, 'unSignedUser', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'user', 1, 'ROLE_NEED_MORE_INFO');
