version: "3.7"
services:
  cherrypick-db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cherrypick
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=cherrypick-svc
      - MYSQL_PASSWORD=cherrypick-pass
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql
  cherrypick-redis:
    image: redis:6.0.2
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379
    ports:
      - 6379:6379
    platform: linux/amd64
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/users.acl:/usr/local/etc/redis/users.acl:rw