### 로그인
POST http://localhost:8080/user/v1/auth/authenticate
Content-Type: application/json

{
  "providerId": "user",
  "password": "admin"
}
> {%
 client.global.set("jwtToken", response.body.data.accessToken);
 %}

### 토큰 재발행
POST http://localhost:8080/user/v1/auth/reissue
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImNwIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY1MzYwMDIwNX0.1S782ib6nb9Gx5fvn7oGNbrvPO2lDWrTsMcKEJrcVxaV1BFxzhjn6wRcW0DPnEZYpEgOAUIBmz2XAvZpmKfzhw",
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImNwIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY1NDgwMjYwNX0.N5_TDpgrC04jl2ca2mDItGI2RVmjxSv0Zbanm_pFrghalhobPtyEi9EAoSwyuhHeXi2SGfVEY37PU_UWj8eZJA"
}


### 회원가입
PATCH http://localhost:8080/user/v1/auth/sign-up
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "job": "backend",
  "career": "LESS_THAN_1YEARS",
  "knownPath": "search"
}