### 로그인
POST http://localhost:8080/user/v1/auth/authenticate
Content-Type: application/json

{
  "providerId": "admin",
  "password": "admin"
}
> {%
 client.global.set("jwtToken", response.body.data.accessToken);
 %}

### 토큰 재발행
POST http://localhost:8080/user/v1/auth/reissue
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiY3AiOiJST0xFX0FETUlOIiwiZXhwIjoxNjU3OTcxODk0fQ.tA9gt7xVUHBfONxYSycr1m8TDOlxOFwrTZGFzItigR9mv4Zii2X1KjFJPql-_GJqscPiXgmArXtOHS2D4lTanw",
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiY3AiOiJST0xFX0FETUlOIiwiZXhwIjoxNjU5MTc0Mjk0fQ.OoTOvnRsh7dobFOM6-2ecW7l9syI30d5MfVxgPAG3JSxUWc5OsprGESlTtO5v3VOZTR_ozgeqCBW3q3LA8xW7w"
}


### 회원가입
PATCH http://localhost:8080/user/v1/auth/sign-up
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "job": "backend",
  "career": "LESS_THAN_1YEARS",
  "knownPath": "search"
}