### 로그인
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "providerId": "admin",
  "password": "admin"
}




### 토큰 재발행
POST http://localhost:8080/api/v1/auth/reissue
Content-Type: application/json

{
"accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImNwIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY1MDc4Mjc4NX0.mPcLtqGIM6VEmWQ-Khrq_Ja2Y653bQlaWpDjPg3CoOwZIJepeXhFZ2kCMPqjmtHZVpTo6jTbAk35AUjA0Y7eEQ",
"refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImNwIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY1MTk4NTE4NX0.66VO7kcXOfQnet8TCEDHvM91J6fip2GNbSuXiTmwR5Xbz9dWHcA-BqQQ-D1lLyWy0YybQ8nRBL-leiopd7Cqgg"
}