GET http://localhost:8080/api/v1/hello
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiY3AiOiJST0xFX1VTRVIiLCJleHAiOjE2NDY3NDU1MTZ9.df5S7pxTyYBPT1x63f2hjZbIk4JSHOfVtD6tMIseZa_ZQLhxIkUa3K3CmRktlG41y2t5LdbQAZjTXzFcx3KuQg