### 강의 리스트 조회 (메인화면 강의리스트, HOT 6, 강의검색)
GET http://localhost:8080/user/v1/lectures?page=0&size=6&sort=price,asc
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### 강의 상세 내용 조회
GET http://localhost:8080/user/v1/lectures/2
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### 내 북마크 강의 조회
GET http://localhost:8080/user/v1/lectures/bookmark?page=0&size=6&sort=price,asc
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### 강의 생성
POST http://localhost:8080/admin/v1/lectures
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "desktopImgUrl": "desktopImgUrl",
  "tabletImgUrl": "tabletImgUrl",
  "mobileImgUrl": "mobile" ,
  "thirdCategories": [1,2],
  "name":  "강의",
  "isOffline": "true",
  "lectureCompany": "test" ,
  "originLink": "test",
  "price": 1000,
  "info": "test",
  "hashTags": ["java","c#"],
  "lecturers":["김영한","백기선"]
}

### 강의 수정
PATCH http://localhost:8080/admin/v1/lectures/1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "desktopImgUrl": "desktopImgUrl",
  "tabletImgUrl": "tabletImgUrl",
  "mobileImgUrl": "mobile" ,
  "thirdCategories": [1],
  "name":  "강의",
  "isOffline": "true",
  "lectureCompany": "test" ,
  "originLink": "test",
  "price": 1000,
  "info": "test",
  "hashTags": ["java","c#"],
  "lecturers":["김영한","백기선"]
}