### 유저 정보 조회
GET http://localhost:8080/user/v1/user
Content-Type: application/json
Authorization: Bearer {{jwtToken}}


### 회원 탈퇴
PATCH http://localhost:8080/user/v1/sign-out
Content-Type: application/json
Authorization: Bearer {{jwtToken}}



### 유저 리스트 조회
GET http://localhost:8080/user/v1/users
Content-Type: application/json
Authorization: Bearer {{jwtToken}}


### 유저 통계 조회
GET http://localhost:8080/admin/v1/user/statistics
Content-Type: application/json
Authorization: Bearer {{jwtToken}}