# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Docer build
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker build -t cherrypick-api .
        docker tag cherrypick-api dhdydtn91/cherrypick-api
        docker push dhdydtn91/cherrypick-api
    - name: Depoly
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ubuntu
        password: ${{ secrets.LIGHTSAIL_PASSWORD }}
        #key: ${{ secrets.PRIVATE_KEY }}
        #envs: GITHUB_SHA
        port : 22
        script: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker pull dhdydtn91/cherrypick-api
          docker tag cherrypick-api dhdydtn91/cherrypick-api
          docker stop server
          docker run -d --rm --name server -p 80:8080 cherrypick-api